### ISSUE TITLE
Default display state of OK/KO/skipped sections

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres-isomorphe#76]
Which section is expanded (amongst OK, KO, skipped) depends on which sections appear. It can be confusing to have different sections expand on different runs.

I found especially confusing the case where the skipped section (containing only "Pas de modification lors de la transformation") is expanded instead of the ok section.

IMO, two better behaviors : 
1. We expand everything and let the user collapse if they want to.
2. We only expand the KO section, always leaving OK/skipped folded. If there's no KO, then everything is folded by default.

**Comment by abulte** [comment]
Expand everything 🗳

**Comment by abulte** [comment]
But we can't :-/ Its not how a (DSFR) accordion works, only one element can be uncollapsed at a given time. Let's do 2 then.

**Comment by streino** [comment]
Can you fold them all? That's a 3rd possibility.

**Comment by streino** [comment]
Damn, now we have to decide... My worry is if we expand KO, user might always overlook the other sections. If we fold everything, maybe it'll force them to look around more?

The tricky part is the "skipped" section, which in most cases will be irrelevant (nothing to do) but sometimes might hide something (skipped because xxx) ? Or we have to make sure those end up in errors (might make more sense), in which case expanding KO only (option 2) would work.

**Comment by abulte** [comment]
I think everything collapsed is OK. We're ordering them the right way: errors, skipped, successes. Everything collapsed will probably entice users to see what's in every block.

**Comment by streino** [comment]
Let's do that then!
